### ISSUE TITLE
Update existing AWS account

### ISSUE THREAD

**Issue by szinck1** [komiserio/komiser-ee#1]
I created an AWS account, when I clicked Save I get `Account with doesnt not exist`. 

Not sure what this means, maybe I pasted in the wrong AWS key?  It's not obvious to me how I can update or remove an account.

**Comment by mlabouardy** [comment]
Hello @szinck1 
You can now remove a cloud account -> https://headwayapp.co/komiser-ee-changelog?utm_medium=widget
